import type { MockResident } from '@/lib/types/mock-data';

export const mockResidents: MockResident[] = [
  {
    id: 'res-001',
    name: 'Ahmad Razif',
    age: 78,
    room: 'A-01',
    status: 'stable',
    vitals: {
      heartRate: { value: 72, unit: 'bpm', status: 'normal' },
      spo2: { value: 98, unit: '%', status: 'normal' },
      bloodPressure: { systolic: 122, diastolic: 78, status: 'normal' },
      temperature: { value: 36.6, unit: '°C', status: 'normal' },
    },
    conditions: ['Hypertension', 'Type 2 Diabetes'],
    lastUpdated: '2 min ago',
  },
  {
    id: 'res-002',
    name: 'Siti Hajar Binti Malik',
    age: 82,
    room: 'A-03',
    status: 'warning',
    vitals: {
      heartRate: { value: 88, unit: 'bpm', status: 'normal' },
      spo2: { value: 96, unit: '%', status: 'normal' },
      bloodPressure: { systolic: 148, diastolic: 94, status: 'high' },
      temperature: { value: 36.9, unit: '°C', status: 'normal' },
    },
    conditions: ['Hypertension', 'Osteoporosis'],
    lastUpdated: '5 min ago',
  },
  {
    id: 'res-003',
    name: 'Mohd Farid Ismail',
    age: 71,
    room: 'B-02',
    status: 'alert',
    vitals: {
      heartRate: { value: 118, unit: 'bpm', status: 'high' },
      spo2: { value: 91, unit: '%', status: 'low' },
      bloodPressure: { systolic: 158, diastolic: 102, status: 'high' },
      temperature: { value: 37.1, unit: '°C', status: 'normal' },
    },
    conditions: ['COPD', 'Hypertension', 'Atrial Fibrillation'],
    lastUpdated: 'Just now',
  },
  {
    id: 'res-004',
    name: 'Rokiah Binti Yusof',
    age: 85,
    room: 'B-04',
    status: 'stable',
    vitals: {
      heartRate: { value: 68, unit: 'bpm', status: 'normal' },
      spo2: { value: 97, unit: '%', status: 'normal' },
      bloodPressure: { systolic: 118, diastolic: 72, status: 'normal' },
      temperature: { value: 36.4, unit: '°C', status: 'normal' },
    },
    conditions: ['Dementia (Mild)', 'Arthritis'],
    lastUpdated: '8 min ago',
  },
  {
    id: 'res-005',
    name: 'Hamdan Ibrahim',
    age: 69,
    room: 'C-01',
    status: 'critical',
    vitals: {
      heartRate: { value: 128, unit: 'bpm', status: 'high' },
      spo2: { value: 88, unit: '%', status: 'critical' },
      bloodPressure: { systolic: 172, diastolic: 108, status: 'high' },
      temperature: { value: 37.4, unit: '°C', status: 'normal' },
    },
    conditions: ['Heart Failure', 'COPD', 'Type 2 Diabetes'],
    lastUpdated: 'Just now',
  },
  {
    id: 'res-006',
    name: 'Noraini Mat Ali',
    age: 76,
    room: 'C-03',
    status: 'warning',
    vitals: {
      heartRate: { value: 82, unit: 'bpm', status: 'normal' },
      spo2: { value: 95, unit: '%', status: 'normal' },
      bloodPressure: { systolic: 132, diastolic: 84, status: 'normal' },
      temperature: { value: 38.1, unit: '°C', status: 'high' },
    },
    conditions: ['Urinary Tract Infection', 'Hypertension'],
    lastUpdated: '3 min ago',
  },
];
